In [1]:
## 1-d deminsional array:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [2]:
## 2-d dimensional array:
c = np.array([[1,2,3,4],[1,2,3,4]])
c


array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [3]:
#### 3-d dimensional array:
d = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
d

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [4]:
c.ndim #### ndim is used to find the dimensions of your given array.

2

In [5]:
a = np.array([1,2,43,4],ndmin =10)
a

array([[[[[[[[[[ 1,  2, 43,  4]]]]]]]]]])

In [6]:
### accessing of elements from an array:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
a[0]

1

In [8]:
a[-1]

4

In [9]:
a[3]

4

In [10]:
### accessing elements from a 2-d array:
c


array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [11]:
c[0:2,0:2]

array([[1, 2],
       [1, 2]])

In [12]:
c[1:3,1:3]

array([[2, 3]])

In [13]:
c[0:2, 0:3]

array([[1, 2, 3],
       [1, 2, 3]])

In [14]:
c[1,1:3]

array([2, 3])

In [15]:
c = np.array([[0,0,0,0,0],[0,1,1,1,0],[0,1,5,1,0],[0,1,1,1,0],[0,0,0,0,0]])
c

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 5, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [16]:
### accessing elemnts from 3-d array:
d


array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [17]:
d[0,0,2:] ### array_name[2-d array index,row_index,slicing/particular element index]

array([3, 4])

In [18]:
d[1,1,2:]

array([3, 4])

In [19]:
d[:,:,2:]

array([[[3, 4],
        [3, 4]],

       [[3, 4],
        [3, 4]]])

In [20]:
### shape of an array: 
a = np.array([[1,2,4,5],[1,2,3,4]])
a

array([[1, 2, 4, 5],
       [1, 2, 3, 4]])

In [21]:
a.shape

(2, 4)

In [22]:
a= np.array([1,2,3,4])
a.shape

(4,)

In [23]:
d.shape

(2, 2, 4)

In [24]:
### Reshape of an array:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
a.reshape(2,6) ### array_name.reshape(rows,columns)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [27]:
a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
a.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [30]:
### converting 1-d to 3-d : 
a.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [31]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [32]:
a.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [33]:
### if the unknown dimension:
a = np.array([1,2,3,4,5,6,7,8])
a.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
a.reshape(2,-1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
a= np.array([1,2,3,4,5,6,7])

In [36]:
#### iterating arrays:
### 1-d array: 
a = np.array([1,2,3])
for x in a:
    print(x)

1
2
3


In [37]:
### 2-d array: 
b = np.arange(1,11)
b=b.reshape(2,5)
for x in b:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [38]:
for x in b:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [39]:
d

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [40]:
for x in d:
    print(x)

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]]


In [41]:
for x in d:
    for y in x:
        for z in y:
            print(z,end= " ")

1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 

In [43]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [44]:
### Joining of arrays:
## 1-d array:
a = np.arange(1,6)
b = np.arange(6,11)
c = np.concatenate((a,b))
c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.ones((2,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
### 2-d array:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b))
c


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
### stastical concepts in numpy:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
a


array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [49]:
np.amin(a)

2

In [50]:
np.amin(a,1)

array([3, 3, 2])

In [51]:
np.min(a)

2

In [52]:
np.max(a)

9

In [53]:
np.amax(a)

9

In [54]:
a.mean() ### mean

5.0

In [55]:
a.var() ### variance

5.333333333333333

In [56]:
a.var() ### variance

5.333333333333333

In [57]:
np.median(a) ## median

4.0

In [58]:
np.average(a)

5.0

In [59]:
np.average(a,1) ### calculating average from each row
np.average(a,0) ### calculating average from each column

array([4.33333333, 5.        , 5.66666667])

In [60]:
### math operations:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [61]:
a.sum() ### sum of all elements

45

In [62]:
np.sqrt(a) ### square root

array([[1.73205081, 2.64575131, 2.23606798],
       [2.82842712, 2.        , 1.73205081],
       [1.41421356, 2.        , 3.        ]])

In [63]:
np.ceil(a)

array([[3., 7., 5.],
       [8., 4., 3.],
       [2., 4., 9.]])

In [64]:
np.floor(a)

array([[3., 7., 5.],
       [8., 4., 3.],
       [2., 4., 9.]])

In [65]:
np.exp(a)

array([[2.00855369e+01, 1.09663316e+03, 1.48413159e+02],
       [2.98095799e+03, 5.45981500e+01, 2.00855369e+01],
       [7.38905610e+00, 5.45981500e+01, 8.10308393e+03]])

In [66]:
np.log(a)

array([[1.09861229, 1.94591015, 1.60943791],
       [2.07944154, 1.38629436, 1.09861229],
       [0.69314718, 1.38629436, 2.19722458]])

In [67]:
np.sin(a)

array([[ 0.14112001,  0.6569866 , -0.95892427],
       [ 0.98935825, -0.7568025 ,  0.14112001],
       [ 0.90929743, -0.7568025 ,  0.41211849]])

In [68]:
np.cos(a)


array([[-0.9899925 ,  0.75390225,  0.28366219],
       [-0.14550003, -0.65364362, -0.9899925 ],
       [-0.41614684, -0.65364362, -0.91113026]])

In [69]:
np.tan(a)

array([[-0.14254654,  0.87144798, -3.38051501],
       [-6.79971146,  1.15782128, -0.14254654],
       [-2.18503986,  1.15782128, -0.45231566]])

In [70]:
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [71]:
np.remainder(a,1)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [72]:
np.log2(a)

array([[1.5849625 , 2.80735492, 2.32192809],
       [3.        , 2.        , 1.5849625 ],
       [1.        , 2.        , 3.169925  ]])

In [73]:
np.log10(a)

array([[0.47712125, 0.84509804, 0.69897   ],
       [0.90308999, 0.60205999, 0.47712125],
       [0.30103   , 0.60205999, 0.95424251]])

In [74]:
np.degrees(a)

array([[171.88733854, 401.07045659, 286.47889757],
       [458.3662361 , 229.18311805, 171.88733854],
       [114.59155903, 229.18311805, 515.66201562]])

In [75]:
help(math.acos)

Help on built-in function acos in module math:

acos(...)
    acos(x)
    
    Return the arc cosine (measured in radians) of x.

